### Đăng ký tài khoản
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "dinhdn123",
    "password": "123"
}

### Đăng nhập
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "dinhdn",
    "password": "123"
}

### Tạo mới công việc
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmQ4Y2RiZjEzN2RhMmVkNzI2Y2M4YWYiLCJpYXQiOjE2NTk4OTA3MzV9.GhMQCJ8_maCatAyPmZlgBWoFvUOF4hbT4D4MJSPAJjo

{
    "title": "Học REDUX (+Toolkit)",
    "description": "Tìm hiểu từ khái niệm tới lý do, kiến trúc của REDUX và những ưu/nhược khi sử dụng Redux trong một dự án React. Chúng ta sẽ xây dựng một ứng dụng demo bằng REDUX và REDUX Toolkit để có thể thấy rõ được những cải tiến mà REDUX Toolkit mang lại",
    "url": "https://www.youtube.com/watch?v=g_K1w8e0lLo"
}

### Lấy toàn bộ công việc của user đang đăng nhập
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmQ4Y2RiZjEzN2RhMmVkNzI2Y2M4YWYiLCJpYXQiOjE2NTgzOTM1ODZ9.qmD2f2df_cXTHSgzqmyqm6jO32yKAVwZN_wBfyoGu44

### Chỉnh sửa công việc
PUT http://localhost:5000/api/posts/62d915b5ef70de40e15baa61
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmQ4Y2RiZjEzN2RhMmVkNzI2Y2M4YWYiLCJpYXQiOjE2NTg0NjMwMjF9.1A1CuLNvLJ-5pcpH6_dQl4AUWubeC19ICAEmGFIQOWU

{
    "title": "Tạo ChatApp đơn giản",
    "description": "Tạo ChatApp đơn giản với TS, NEXTJS, FIREBASE,...!!",
    "url": "https://google.com"
}

### Xoá công việc
DELETE http://localhost:5000/api/posts/62da19e303f6505e08466be5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmQ4Y2RiZjEzN2RhMmVkNzI2Y2M4YWYiLCJpYXQiOjE2NTg0NjMwMjF9.1A1CuLNvLJ-5pcpH6_dQl4AUWubeC19ICAEmGFIQOWU
